---
title: 'Makefile'
---
%%{
  init: {
    "fontFamily": "monospace",
    "logLevel": "info",
    "flowchart": {
    }
  }
}%%
graph TD
  %% BEGIN flowchart
  staticanalysis["static-analysis"] -. chain .-> toxstaticanalysis["tox-static-analysis"]
  stest["stest"] -. chain .-> toxstest["tox-stest"]
  toxstaticanalysis["tox-static-analysis"] -. chain .-> tox["tox-%"]
  utest["utest"] -. chain .-> toxutest["tox-utest"]
  toxitest["tox-itest"] -. chain .-> tox["tox-%"]
  toxstest["tox-stest"] -. chain .-> tox["tox-%"]
  testunits["test-units"] -. chain .-> utest["utest"]
  toxnormalize["tox-normalize"] -. chain .-> tox["tox-%"]
  toxutest["tox-utest"] -. chain .-> tox["tox-%"]
  plan["plan"] -. chain .-> docsplan["docs-plan"]
  apply["apply"] -. chain .-> docsapply["docs-apply"]
  test["test"] ----> testunits["test-units"]
  test["test"] ----> testintegrations["test-integrations"]
  test["test"] ----> smoketest["smoke-test"]
  build["build"] -. chain .-> pybuild["py-build"]
  smoketest["smoke-test"] -. chain .-> stest["stest"]
  pybuild["py-build"] ----> pyclean["py-clean"]
  normalize["normalize"] -. chain .-> toxnormalize["tox-normalize"]
  release["release"] ----> clean["clean"]
  release["release"] ----> normalize["normalize"]
  release["release"] ----> staticanalysis["static-analysis"]
  release["release"] ----> test["test"]
  release["release"] ----> pypirelease["pypi-release"]
  clean["clean"] -. chain .-> pyclean["py-clean"]
  docs["docs"] -. chain .-> docsapply["docs-apply"]
  init["init"] -. chain .-> pyinit["py-init"]
  testintegrations["test-integrations"] -. chain .-> itest["itest"]
  lint["lint"] -. chain .-> staticanalysis["static-analysis"]
  itest["itest"] -. chain .-> toxitest["tox-itest"]
  subgraph core
    staticanalysis["static-analysis"]
    plan["plan"]
    apply["apply"]
    test["test"]
    build["build"]
    normalize["normalize"]
    release["release"]
    clean["clean"]
    docs["docs"]
  end
  %% END flowchart
